version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: thenecromancerx/docker-python-serverless
    docker:
      - image: cibuilds/aws:latest
jobs:
  build-publish:
    executor: docker-publisher
    parameters:
      distro:
        default: "alpine"
        description: Docker image distro
        type: enum
        enum: ["alpine", "slim", "buster", "stretch"]
      python_version:
        description: Supported Lambda Python Version
        default: "3.8"
        type: enum
        enum: ["3.6", "3.7", "3.8"]
      node_version:
        description: Node Version
        default: "15"
        type: enum
        enum: ["12", "14", "15"]
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            if [[ << parameters.distro >> = 'buster' ]]
            then
              docker build -t $IMAGE_NAME:python<< parameters.python_version >>-nodejs<< parameters.node_version >>-buster --build-arg TAG=python<< parameters.python_version >>-nodejs<< parameters.node_version >> . -f Dockerfile
            elif [[ << parameters.distro >> = 'alpine' ]]
            then
              docker build -t $IMAGE_NAME:python<< parameters.python_version >>-nodejs<< parameters.node_version >>-alpine --build-arg TAG=python<< parameters.python_version >>-nodejs<< parameters.node_version >>-alpine . -f alpine.Dockerfile
            else
              docker build -t $IMAGE_NAME:python<< parameters.python_version >>-nodejs<< parameters.node_version >>-<< parameters.distro >> --build-arg TAG=python<< parameters.python_version >>-nodejs<< parameters.node_version >>-<< parameters.distro >> . -f Dockerfile
            fi
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            docker push $IMAGE_NAME:python<< parameters.python_version >>-nodejs<< parameters.node_version >>-<< parameters.distro >>

            if [[ << parameters.distro >> = 'alpine' ]] 
            then
              docker tag $IMAGE_NAME:python<< parameters.python_version >>-nodejs<< parameters.node_version >>-<< parameters.distro >> $IMAGE_NAME:python<< parameters.python_version >>-nodejs<< parameters.node_version >>
              docker push $IMAGE_NAME:python<< parameters.python_version >>-nodejs<< parameters.node_version >>
            fi

            if [[ << parameters.distro >> = 'alpine' ]] && [[ << parameters.node_version >> = '15' ]]
            then
              docker tag $IMAGE_NAME:python<< parameters.python_version >>-nodejs<< parameters.node_version >>-<< parameters.distro >> $IMAGE_NAME:python<< parameters.python_version >>
              docker push $IMAGE_NAME:python<< parameters.python_version >>
            fi

            if [[ << parameters.distro >> = 'alpine' ]] && [[ << parameters.node_version >> = '15' ]] && [[ << parameters.python_version >> = '3.8' ]]
            then
              docker tag $IMAGE_NAME:python<< parameters.python_version >>-nodejs<< parameters.node_version >>-<< parameters.distro >> $IMAGE_NAME:latest
              docker push $IMAGE_NAME:latest
            fi

workflows:
  version: 2
  build-latest-on-commit:
    jobs:
      - build-publish:
          distro: "alpine"
          python_version: "3.8"
          node_version: "15"
          filters:
            branches:
              only: master
  build-python3.8-nodejs15:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-publish:
          distro: "alpine"
          python_version: "3.8"
          node_version: "15"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "slim"
          python_version: "3.8"
          node_version: "15"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "buster"
          python_version: "3.8"
          node_version: "15"
          filters:
            branches:
              only: master
      # - build-publish:
      #     distro: "stretch"
      #     python_version: "3.8"
      #     node_version: "15"
      #     filters:
      #       branches:
      #         only: master
  build-python3.7-nodejs15:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-publish:
          distro: "alpine"
          python_version: "3.7"
          node_version: "15"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "slim"
          python_version: "3.7"
          node_version: "15"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "buster"
          python_version: "3.7"
          node_version: "15"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "stretch"
          python_version: "3.7"
          node_version: "15"
          filters:
            branches:
              only: master
  build-python3.6-nodejs15:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-publish:
          distro: "alpine"
          python_version: "3.6"
          node_version: "15"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "slim"
          python_version: "3.6"
          node_version: "15"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "buster"
          python_version: "3.6"
          node_version: "15"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "stretch"
          python_version: "3.6"
          node_version: "15"
          filters:
            branches:
              only: master
  build-python3.8-nodejs14:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-publish:
          distro: "alpine"
          python_version: "3.8"
          node_version: "14"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "slim"
          python_version: "3.8"
          node_version: "14"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "buster"
          python_version: "3.8"
          node_version: "14"
          filters:
            branches:
              only: master
      # - build-publish:
      #     distro: "stretch"
      #     python_version: "3.8"
      #     node_version: "14"
      #     filters:
      #       branches:
      #         only: master
  build-python3.7-nodejs14:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-publish:
          distro: "alpine"
          python_version: "3.7"
          node_version: "14"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "slim"
          python_version: "3.7"
          node_version: "14"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "buster"
          python_version: "3.7"
          node_version: "14"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "stretch"
          python_version: "3.7"
          node_version: "14"
          filters:
            branches:
              only: master
  build-python3.6-nodejs14:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-publish:
          distro: "alpine"
          python_version: "3.6"
          node_version: "14"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "slim"
          python_version: "3.6"
          node_version: "14"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "buster"
          python_version: "3.6"
          node_version: "14"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "stretch"
          python_version: "3.6"
          node_version: "14"
          filters:
            branches:
              only: master
  build-python3.8-nodejs12:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-publish:
          distro: "alpine"
          python_version: "3.8"
          node_version: "12"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "slim"
          python_version: "3.8"
          node_version: "12"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "buster"
          python_version: "3.8"
          node_version: "12"
          filters:
            branches:
              only: master
      # - build-publish:
      #     distro: "stretch"
      #     python_version: "3.8"
      #     node_version: "12"
      #     filters:
      #       branches:
      #         only: master
  build-python3.7-nodejs12:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-publish:
          distro: "alpine"
          python_version: "3.7"
          node_version: "12"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "slim"
          python_version: "3.7"
          node_version: "12"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "buster"
          python_version: "3.7"
          node_version: "12"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "stretch"
          python_version: "3.7"
          node_version: "12"
          filters:
            branches:
              only: master
  build-python3.6-nodejs12:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-publish:
          distro: "alpine"
          python_version: "3.6"
          node_version: "12"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "slim"
          python_version: "3.6"
          node_version: "12"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "buster"
          python_version: "3.6"
          node_version: "12"
          filters:
            branches:
              only: master
      - build-publish:
          distro: "stretch"
          python_version: "3.6"
          node_version: "12"
          filters:
            branches:
              only: master
